// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_hsASpzmwufMK5Gu9dhwATy7PR6TITo',
    appId: '1:62446329630:web:25b89e2947b54346eef30f',
    messagingSenderId: '62446329630',
    projectId: 'ojt-tracker-fd0a2',
    authDomain: 'ojt-tracker-fd0a2.firebaseapp.com',
    storageBucket: 'ojt-tracker-fd0a2.firebasestorage.app',
    measurementId: 'G-XPKYE4LS3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsQuXriLS002CwUqWtk3Wun8uQXsx7aeg',
    appId: '1:62446329630:android:5ac57e29ee257463eef30f',
    messagingSenderId: '62446329630',
    projectId: 'ojt-tracker-fd0a2',
    storageBucket: 'ojt-tracker-fd0a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3aRkNMXHq9AYLeLolS6hTQG9CSUE8oPI',
    appId: '1:62446329630:ios:2473ed1164e0484aeef30f',
    messagingSenderId: '62446329630',
    projectId: 'ojt-tracker-fd0a2',
    storageBucket: 'ojt-tracker-fd0a2.firebasestorage.app',
    iosBundleId: 'com.example.ojtTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3aRkNMXHq9AYLeLolS6hTQG9CSUE8oPI',
    appId: '1:62446329630:ios:2473ed1164e0484aeef30f',
    messagingSenderId: '62446329630',
    projectId: 'ojt-tracker-fd0a2',
    storageBucket: 'ojt-tracker-fd0a2.firebasestorage.app',
    iosBundleId: 'com.example.ojtTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB_hsASpzmwufMK5Gu9dhwATy7PR6TITo',
    appId: '1:62446329630:web:e9a31c018e282687eef30f',
    messagingSenderId: '62446329630',
    projectId: 'ojt-tracker-fd0a2',
    authDomain: 'ojt-tracker-fd0a2.firebaseapp.com',
    storageBucket: 'ojt-tracker-fd0a2.firebasestorage.app',
    measurementId: 'G-3SR3J2HTZZ',
  );
}
